#!/usr/bin/env python3
"""Bake the M5StickS3 UI sounds into a C include.

The board has no filesystem and no downloader: a sound it cannot address as
an array in flash is a sound it does not have. Sources: the wake chime is
the official Home Assistant Voice PE press asset (ESPHome project,
Apache-2.0), converted to this pipeline's 16 kHz mono PCM16; the end-of-call
announcement is an OpenAI TTS render in marin — the same voice the assistant
answers in. The chime is NOT trimmed here: this board's half-duplex fence
means the speaker physically cannot play into an open microphone, so the
full ding costs nothing (and a talk hold that begins mid-chime deletes the
playback channel and the rest of the chime with it). Regenerate with:

  python3 make-sounds.py <dir-with-wavs>  > m5sticks3_sounds_generated.inc
"""
import struct, sys, pathlib

NAMES = [
    ("chime_press", "center_button_press.wav"),
    ("chime_ended", "call_ended.wav"),
]

# LOUDER THAN SPEECH ON PURPOSE. The chime and "call ended" are feedback, not
# conversation: they must land at the volume a person set for answers even
# though the source WAV is mastered quiet. x2.5 with hard clipping measured
# audible-but-not-harsh on this speaker; the saturation guard keeps a hot
# source from wrapping.
GAIN_NUMERATOR = 5
GAIN_DENOMINATOR = 2

def apply_gain(pcm):
    import struct as _s
    samples = _s.unpack("<%dh" % (len(pcm) // 2), pcm)
    scaled = []
    for sample in samples:
        boosted = sample * GAIN_NUMERATOR // GAIN_DENOMINATOR
        scaled.append(max(-32768, min(32767, boosted)))
    return _s.pack("<%dh" % len(scaled), *scaled)


def pcm_of(path):
    raw = path.read_bytes()
    offset = 12
    while offset + 8 <= len(raw):
        cid = raw[offset:offset+4]
        size = struct.unpack("<I", raw[offset+4:offset+8])[0]
        if cid == b"data":
            return raw[offset+8:offset+8+size]
        offset += 8 + size + (size % 2)
    raise SystemExit(f"no data chunk in {path}")

src = pathlib.Path(sys.argv[1])
print("/* GENERATED by make-sounds.py — do not edit. 16 kHz mono PCM16LE. */")
for cname, fname in NAMES:
    pcm = apply_gain(pcm_of(src / fname))
    print(f"static const uint8_t m5sticks3_sound_{cname}[] = {{")
    for i in range(0, len(pcm), 24):
        print("  " + ",".join(str(b) for b in pcm[i:i+24]) + ",")
    print("};")
