#!/usr/bin/env python3
"""Bake the Waveshare AMOLED UI sounds into a C include.

The board has no filesystem and no downloader: a sound it cannot address as
an array in flash is a sound it does not have. Sources: the wake chime is
the official Home Assistant Voice PE press asset (ESPHome project,
Apache-2.0), converted to this pipeline's 16 kHz mono PCM16; the end-of-call
announcement is an OpenAI TTS render in marin — the same voice the assistant
answers in. Regenerate with:

  python3 make-sounds.py <dir-with-wavs>  > waveshare_sounds_generated.inc
"""
import struct, sys, pathlib

NAMES = [
    ("chime_press", "center_button_press.wav"),
    ("chime_ended", "call_ended.wav"),
]

# THE WAKE CHIME IS TRIMMED TO ITS AUDIBLE BODY, as on the StackChan but for
# a starker reason.
#
# The stock asset is 1.37 s: a ding whose envelope is below -25 dBFS by 0.4 s
# and digitally silent from 0.8 s. On this board the wake gesture is
# press-AND-HOLD: the upper button's press edge wakes the session and its
# level is the microphone, so the person is invited to speak the moment they
# press — and this board has NO echo cancellation of any kind, so every
# millisecond the speaker rings past the call's first captured frame goes up
# the uplink verbatim, on top of the person's opening words. 0.4 s keeps the
# ding a person hears and is finished before the dial completes; the 40 ms
# fade replaces the decay the trim removed so the cut does not click.
WAKE_TRIM_SAMPLES = 6400  # 0.4 s at 16 kHz
WAKE_FADE_SAMPLES = 640  # 40 ms

def trim_wake(pcm):
    samples = list(struct.unpack("<%dh" % (len(pcm) // 2), pcm))
    samples = samples[:WAKE_TRIM_SAMPLES]
    for i in range(WAKE_FADE_SAMPLES):
        j = len(samples) - WAKE_FADE_SAMPLES + i
        samples[j] = samples[j] * (WAKE_FADE_SAMPLES - 1 - i) // WAKE_FADE_SAMPLES
    return struct.pack("<%dh" % len(samples), *samples)

# LOUDER THAN SPEECH ON PURPOSE. The chime and "call ended" are feedback, not
# conversation: they must land at the volume a person set for answers even
# though the source WAV is mastered quiet. x2.5 with hard clipping measured
# audible-but-not-harsh on this speaker; the saturation guard keeps a hot
# source from wrapping.
GAIN_NUMERATOR = 5
GAIN_DENOMINATOR = 2

def apply_gain(pcm):
    import struct as _s
    samples = _s.unpack("<%dh" % (len(pcm) // 2), pcm)
    scaled = []
    for sample in samples:
        boosted = sample * GAIN_NUMERATOR // GAIN_DENOMINATOR
        scaled.append(max(-32768, min(32767, boosted)))
    return _s.pack("<%dh" % len(scaled), *scaled)


def pcm_of(path):
    raw = path.read_bytes()
    offset = 12
    while offset + 8 <= len(raw):
        cid = raw[offset:offset+4]
        size = struct.unpack("<I", raw[offset+4:offset+8])[0]
        if cid == b"data":
            return raw[offset+8:offset+8+size]
        offset += 8 + size + (size % 2)
    raise SystemExit(f"no data chunk in {path}")

src = pathlib.Path(sys.argv[1])
print("/* GENERATED by make-sounds.py — do not edit. 16 kHz mono PCM16LE. */")
for cname, fname in NAMES:
    pcm = pcm_of(src / fname)
    if cname == "chime_press":
        pcm = trim_wake(pcm)
    pcm = apply_gain(pcm)
    print(f"static const uint8_t waveshare_sound_{cname}[] = {{")
    for i in range(0, len(pcm), 24):
        print("  " + ",".join(str(b) for b in pcm[i:i+24]) + ",")
    print("};")
