#!/usr/bin/env python3
"""Bake the HAVPE UI sounds into a C include.

The board has no filesystem and no downloader: a sound it cannot address as
an array in flash is a sound it does not have. Sources: the wake chime is
the official Home Assistant Voice PE press asset (ESPHome project,
Apache-2.0), converted to this pipeline's 16 kHz mono PCM16; the end-of-call
announcement and the four mode announcements are OpenAI TTS renders in
marin — the same voice the assistant answers in. Regenerate with:

  python3 make-sounds.py <dir-with-wavs>  > havpe_sounds_generated.inc
"""
import struct, sys, pathlib

NAMES = [
    ("chime_press", "center_button_press.wav"),
    ("chime_ended", "call_ended.wav"),
    ("mode_grok_ptt", "mode1.wav"),
    ("mode_grok_vad", "mode2.wav"),
    ("mode_openai_ptt", "mode3.wav"),
    ("mode_openai_vad", "mode4.wav"),
]

def pcm_of(path):
    raw = path.read_bytes()
    offset = 12
    while offset + 8 <= len(raw):
        cid = raw[offset:offset+4]
        size = struct.unpack("<I", raw[offset+4:offset+8])[0]
        if cid == b"data":
            return raw[offset+8:offset+8+size]
        offset += 8 + size + (size % 2)
    raise SystemExit(f"no data chunk in {path}")

src = pathlib.Path(sys.argv[1])
print("/* GENERATED by make-sounds.py — do not edit. 16 kHz mono PCM16LE. */")
for cname, fname in NAMES:
    pcm = pcm_of(src / fname)
    print(f"static const uint8_t havpe_sound_{cname}[] = {{")
    for i in range(0, len(pcm), 24):
        print("  " + ",".join(str(b) for b in pcm[i:i+24]) + ",")
    print("};")
print("struct havpe_sound { const uint8_t *pcm; uint32_t bytes; };")
print("static const struct havpe_sound havpe_mode_sounds[4] = {")
for cname in ["mode_grok_ptt", "mode_grok_vad", "mode_openai_ptt", "mode_openai_vad"]:
    print(f"  {{ havpe_sound_{cname}, sizeof(havpe_sound_{cname}) }},")
print("};")
