/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// TanStack Router generates the `as any` route-update assertions below because

// the route IDs are registered by the later FileRoutesByPath declaration; the

// generated declaration makes those otherwise-unrepresentable assertions safe.

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevicesDeviceIdFirmwareFirmwareVersionRouteImport } from './routes/devices.$deviceId.firmware.$firmwareVersion'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesDeviceIdFirmwareFirmwareVersionRoute =
  DevicesDeviceIdFirmwareFirmwareVersionRouteImport.update({
    id: '/devices/$deviceId/firmware/$firmwareVersion',
    path: '/devices/$deviceId/firmware/$firmwareVersion',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/devices/$deviceId/firmware/$firmwareVersion': typeof DevicesDeviceIdFirmwareFirmwareVersionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/devices/$deviceId/firmware/$firmwareVersion': typeof DevicesDeviceIdFirmwareFirmwareVersionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/devices/$deviceId/firmware/$firmwareVersion': typeof DevicesDeviceIdFirmwareFirmwareVersionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/devices/$deviceId/firmware/$firmwareVersion'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/devices/$deviceId/firmware/$firmwareVersion'
  id: '__root__' | '/' | '/devices/$deviceId/firmware/$firmwareVersion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevicesDeviceIdFirmwareFirmwareVersionRoute: typeof DevicesDeviceIdFirmwareFirmwareVersionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices/$deviceId/firmware/$firmwareVersion': {
      id: '/devices/$deviceId/firmware/$firmwareVersion'
      path: '/devices/$deviceId/firmware/$firmwareVersion'
      fullPath: '/devices/$deviceId/firmware/$firmwareVersion'
      preLoaderRoute: typeof DevicesDeviceIdFirmwareFirmwareVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevicesDeviceIdFirmwareFirmwareVersionRoute:
    DevicesDeviceIdFirmwareFirmwareVersionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
