/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root.tsx";
import { Route as AuthRouteImport } from "./routes/_auth.tsx";
import { Route as IndexRouteImport } from "./routes/index.tsx";
import { Route as AuthDevicesDeviceIdFirmwareFirmwareVersionRouteImport } from "./routes/_auth/devices.$deviceId.firmware.$firmwareVersion.tsx";

const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthDevicesDeviceIdFirmwareFirmwareVersionRoute =
  AuthDevicesDeviceIdFirmwareFirmwareVersionRouteImport.update({
    id: "/devices/$deviceId/firmware/$firmwareVersion",
    path: "/devices/$deviceId/firmware/$firmwareVersion",
    getParentRoute: () => AuthRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/devices/$deviceId/firmware/$firmwareVersion": typeof AuthDevicesDeviceIdFirmwareFirmwareVersionRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/devices/$deviceId/firmware/$firmwareVersion": typeof AuthDevicesDeviceIdFirmwareFirmwareVersionRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_auth": typeof AuthRouteWithChildren;
  "/_auth/devices/$deviceId/firmware/$firmwareVersion": typeof AuthDevicesDeviceIdFirmwareFirmwareVersionRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/devices/$deviceId/firmware/$firmwareVersion";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/devices/$deviceId/firmware/$firmwareVersion";
  id:
    | "__root__"
    | "/"
    | "/_auth"
    | "/_auth/devices/$deviceId/firmware/$firmwareVersion";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRoute: typeof AuthRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth/devices/$deviceId/firmware/$firmwareVersion": {
      id: "/_auth/devices/$deviceId/firmware/$firmwareVersion";
      path: "/devices/$deviceId/firmware/$firmwareVersion";
      fullPath: "/devices/$deviceId/firmware/$firmwareVersion";
      preLoaderRoute: typeof AuthDevicesDeviceIdFirmwareFirmwareVersionRouteImport;
      parentRoute: typeof AuthRoute;
    };
  }
}

interface AuthRouteChildren {
  AuthDevicesDeviceIdFirmwareFirmwareVersionRoute: typeof AuthDevicesDeviceIdFirmwareFirmwareVersionRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDevicesDeviceIdFirmwareFirmwareVersionRoute:
    AuthDevicesDeviceIdFirmwareFirmwareVersionRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
