/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root.tsx";
import { Route as IndexRouteImport } from "./routes/index.tsx";
import { Route as AuthRouteImport } from "./routes/_auth.tsx";
import { Route as AuthDevicesDeviceIdRouteImport } from "./routes/_auth/devices.$deviceId.tsx";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthDevicesDeviceIdRoute = AuthDevicesDeviceIdRouteImport.update({
  id: "/devices/$deviceId",
  path: "/devices/$deviceId",
  getParentRoute: () => AuthRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/devices/$deviceId": typeof AuthDevicesDeviceIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/devices/$deviceId": typeof AuthDevicesDeviceIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_auth": typeof AuthRouteWithChildren;
  "/_auth/devices/$deviceId": typeof AuthDevicesDeviceIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/devices/$deviceId";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/devices/$deviceId";
  id: "__root__" | "/" | "/_auth" | "/_auth/devices/$deviceId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRoute: typeof AuthRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth/devices/$deviceId": {
      id: "/_auth/devices/$deviceId";
      path: "/devices/$deviceId";
      fullPath: "/devices/$deviceId";
      preLoaderRoute: typeof AuthDevicesDeviceIdRouteImport;
      parentRoute: typeof AuthRoute;
    };
  }
}

interface AuthRouteChildren {
  AuthDevicesDeviceIdRoute: typeof AuthDevicesDeviceIdRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDevicesDeviceIdRoute: AuthDevicesDeviceIdRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
