#!/usr/bin/env python3
"""Bake the StackChan UI sounds into a C include.

The board has no filesystem and no downloader: a sound it cannot address as
an array in flash is a sound it does not have. Sources: the wake chime is
the official Home Assistant Voice PE press asset (ESPHome project,
Apache-2.0), converted to this pipeline's 16 kHz mono PCM16; the end-of-call
announcement and the two provider announcements are OpenAI TTS renders in
marin — the same voice the assistant answers in. Regenerate with:

  python3 make-sounds.py <dir-with-wavs>  > stackchan_sounds_generated.inc
"""
import struct, sys, pathlib

NAMES = [
    ("chime_press", "center_button_press.wav"),
    ("chime_ended", "call_ended.wav"),
    ("mode_grok", "stackchan_grok.wav"),
    ("mode_openai", "stackchan_openai.wav"),
]

# THE WAKE CHIME IS TRIMMED TO ITS AUDIBLE BODY, on this board only.
#
# The stock asset is 1.37 s: a ding whose envelope is below -25 dBFS by 0.4 s
# and digitally silent from 0.8 s. Every millisecond of it is a millisecond of
# far-end activity through the speaker, and this board's VOIP-mode canceller
# destroys concurrent near speech during far-end activity (see
# stackchan_processor.c) — so the wake chime was erasing the opening words of
# anyone who pressed and spoke immediately, which is the exact gesture the
# chime invites. Proven live 2026-08-20: the same sentence at the same press
# lost its first ~1.4 s with the chime and kept it without. 0.4 s keeps the
# ding a person hears; the 40 ms fade replaces the decay the trim removed so
# the cut does not click.
WAKE_TRIM_SAMPLES = 6400  # 0.4 s at 16 kHz
WAKE_FADE_SAMPLES = 640  # 40 ms

def trim_wake(pcm):
    samples = list(struct.unpack("<%dh" % (len(pcm) // 2), pcm))
    samples = samples[:WAKE_TRIM_SAMPLES]
    for i in range(WAKE_FADE_SAMPLES):
        j = len(samples) - WAKE_FADE_SAMPLES + i
        samples[j] = samples[j] * (WAKE_FADE_SAMPLES - 1 - i) // WAKE_FADE_SAMPLES
    return struct.pack("<%dh" % len(samples), *samples)

def pcm_of(path):
    raw = path.read_bytes()
    offset = 12
    while offset + 8 <= len(raw):
        cid = raw[offset:offset+4]
        size = struct.unpack("<I", raw[offset+4:offset+8])[0]
        if cid == b"data":
            return raw[offset+8:offset+8+size]
        offset += 8 + size + (size % 2)
    raise SystemExit(f"no data chunk in {path}")

src = pathlib.Path(sys.argv[1])
print("/* GENERATED by make-sounds.py — do not edit. 16 kHz mono PCM16LE. */")
for cname, fname in NAMES:
    pcm = pcm_of(src / fname)
    if cname == "chime_press":
        pcm = trim_wake(pcm)
    print(f"static const uint8_t stackchan_sound_{cname}[] = {{")
    for i in range(0, len(pcm), 24):
        print("  " + ",".join(str(b) for b in pcm[i:i+24]) + ",")
    print("};")
print("struct stackchan_sound { const uint8_t *pcm; uint32_t bytes; };")
print("static const struct stackchan_sound stackchan_mode_sounds[2] = {")
for cname in ["mode_grok", "mode_openai"]:
    print(f"  {{ stackchan_sound_{cname}, sizeof(stackchan_sound_{cname}) }},")
print("};")
