#!/usr/bin/env python3
"""Regenerate the avatar sprite atlas C files from committed compact assets.

The five fspp_*_cores3_fine_atlas.c files (and the avatar catalog .inc) are
NOT committed - roughly 4,500 lines of machine-written hex nobody reviews.
What IS committed, per pack, in components/avatar/assets/:

  <pack>.png   one indexed-color sprite map holding every cell's pixels
               (palette index 0 is transparent; the PLTE colors are only a
               viewing aid - the authoritative RGB565 palette is in the JSON)
  <pack>.json  everything else: palette(s), cell geometry and sprite-map
               placement, mouth slot arrays, viseme maps, expression banks,
               both atlas structs' fields, and the catalog entry

Usage (stdlib python3 only, no dependencies):

  python3 apps/kit/firmware/tools/generate-atlases.py            # assets -> src
  python3 apps/kit/firmware/tools/generate-atlases.py extract    # src -> assets

`extract` is the inverse tool that produced the assets from the original
generated C in the first place; it round-trips through the emitter and fails
unless the regenerated C is byte-identical, so it is safe to re-run.

Cell pixels are stored decoded in the PNG. The generator re-encodes each cell
with the exact PackBits dialect face_sprite_sheet.c decodes (run >= 3 becomes
a repeat, literals break before a 3-run, raw wins ties) and rebuilds the blob
by concatenation, reproducing the original byte stream exactly.
"""

from __future__ import annotations

import json
import re
import struct
import sys
import zlib
from pathlib import Path

FIRMWARE = Path(__file__).resolve().parent.parent
SRC = FIRMWARE / "components" / "avatar" / "src"
ASSETS = FIRMWARE / "components" / "avatar" / "assets"
CATALOG_INC = SRC / "face_avatar_catalog_generated.inc"

BANNER = (
    "/* Generated by tools/sprite-pipeline/avatar_pipeline.py. "
    "Do not hand-edit.\n"
    " * Derived sprite data is dedicated to the public domain under CC0 1.0\n"
    " * to the extent of the generator's contribution; see the pack README\n"
    " * for source-art provenance.\n"
    " */\n"
)
CATALOG_BANNER = "/* Generated by avatar_pipeline.py publish. Do not hand-edit. */\n"

DISABLED_EYE = (
    "{ .x = 0, .y = 0, .cell_count = 0, .cells = { FACE_SPRITE_CELL_NONE, "
    "FACE_SPRITE_CELL_NONE, FACE_SPRITE_CELL_NONE, FACE_SPRITE_CELL_NONE, "
    "FACE_SPRITE_CELL_NONE, FACE_SPRITE_CELL_NONE }, .flags = 0, .reserved = 0 }"
)
DISABLED_PUPIL = (
    "{ .x = 0, .y = 0, .min_x = 0, .min_y = 0, .max_x = 0, .max_y = 0, "
    ".cell = FACE_SPRITE_CELL_NONE, .range_x = 0, .range_y = 0 }"
)
DISABLED_BROW = (
    "{ .x = 0, .y = 0, .cell_count = 0, .cells = { FACE_SPRITE_CELL_NONE, "
    "FACE_SPRITE_CELL_NONE, FACE_SPRITE_CELL_NONE, FACE_SPRITE_CELL_NONE, "
    "FACE_SPRITE_CELL_NONE }, .max_lift = 0, .flags = 0 }"
)

SHEET_MAX_WIDTH = 128


# --------------------------------------------------------------------------
# PackBits (the exact dialect decoded by face_sprite_sheet.c)


def packbits(data: bytes) -> bytes:
    result = bytearray()
    index = 0
    while index < len(data):
        run = 1
        while (
            index + run < len(data)
            and data[index + run] == data[index]
            and run < 128
        ):
            run += 1
        if run >= 3:
            result.append(257 - run)
            result.append(data[index])
            index += run
            continue
        start = index
        index += 1
        while index < len(data) and index - start < 128:
            if (
                index + 2 < len(data)
                and data[index] == data[index + 1] == data[index + 2]
            ):
                break
            index += 1
        literal = data[start:index]
        result.append(len(literal) - 1)
        result.extend(literal)
    return bytes(result)


def unpackbits(data: bytes, expected: int) -> bytes:
    out = bytearray()
    pos = 0
    while len(out) < expected:
        if pos >= len(data):
            raise ValueError("PackBits stream truncated")
        control = data[pos]
        pos += 1
        if control == 128:
            continue
        if control > 128:
            if pos >= len(data):
                raise ValueError("PackBits repeat missing byte")
            out.extend(bytes((data[pos],)) * (257 - control))
            pos += 1
        else:
            count = control + 1
            if pos + count > len(data):
                raise ValueError("PackBits literal truncated")
            out.extend(data[pos : pos + count])
            pos += count
    if len(out) != expected or pos != len(data):
        raise ValueError("PackBits stream does not end exactly at cell size")
    return bytes(out)


def encode_cell(pixels: bytes) -> tuple[bytes, int]:
    """Return (data, encoding): PackBits when strictly shorter, else raw."""
    encoded = packbits(pixels)
    if len(encoded) >= len(pixels):
        return pixels, 0
    return encoded, 1


# --------------------------------------------------------------------------
# Minimal indexed-color PNG I/O (stdlib only)


def _png_chunk(tag: bytes, payload: bytes) -> bytes:
    return (
        struct.pack(">I", len(payload))
        + tag
        + payload
        + struct.pack(">I", zlib.crc32(tag + payload) & 0xFFFFFFFF)
    )


def png_write(path: Path, width: int, height: int, pixels: bytes, palette565: list[int]) -> None:
    """8-bit indexed PNG; PLTE is an RGB565->RGB888 expansion for viewing."""
    plte = bytearray()
    for value in palette565:
        r5, g6, b5 = (value >> 11) & 0x1F, (value >> 5) & 0x3F, value & 0x1F
        plte += bytes(((r5 << 3) | (r5 >> 2), (g6 << 2) | (g6 >> 4), (b5 << 3) | (b5 >> 2)))
    raw = bytearray()
    for y in range(height):
        raw.append(0)  # filter: None
        raw += pixels[y * width : (y + 1) * width]
    out = b"\x89PNG\r\n\x1a\n"
    out += _png_chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 3, 0, 0, 0))
    out += _png_chunk(b"PLTE", bytes(plte))
    out += _png_chunk(b"tRNS", b"\x00")  # index 0 is transparent
    out += _png_chunk(b"IDAT", zlib.compress(bytes(raw), 9))
    out += _png_chunk(b"IEND", b"")
    path.write_bytes(out)


def png_read(path: Path) -> tuple[int, int, bytes]:
    """Return (width, height, palette-index bytes). Indexed 8-bit only."""
    blob = path.read_bytes()
    if blob[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError(f"{path}: not a PNG")
    pos, width, height, idat = 8, 0, 0, bytearray()
    while pos < len(blob):
        (length,) = struct.unpack(">I", blob[pos : pos + 4])
        tag = blob[pos + 4 : pos + 8]
        payload = blob[pos + 8 : pos + 8 + length]
        pos += 12 + length
        if tag == b"IHDR":
            width, height, depth, color, _, _, interlace = struct.unpack(">IIBBBBB", payload)
            if (depth, color, interlace) != (8, 3, 0):
                raise ValueError(f"{path}: expected non-interlaced 8-bit indexed PNG")
        elif tag == b"IDAT":
            idat += payload
        elif tag == b"IEND":
            break
    raw = zlib.decompress(bytes(idat))
    stride = width + 1
    out = bytearray()
    prev = bytearray(width)
    for y in range(height):
        row = bytearray(raw[y * stride + 1 : (y + 1) * stride])
        filt = raw[y * stride]
        for x in range(width):
            a = row[x - 1] if x else 0
            b = prev[x]
            c = prev[x - 1] if x else 0
            if filt == 1:
                row[x] = (row[x] + a) & 0xFF
            elif filt == 2:
                row[x] = (row[x] + b) & 0xFF
            elif filt == 3:
                row[x] = (row[x] + (a + b) // 2) & 0xFF
            elif filt == 4:
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                pred = a if pa <= pb and pa <= pc else (b if pb <= pc else c)
                row[x] = (row[x] + pred) & 0xFF
            elif filt != 0:
                raise ValueError(f"{path}: unsupported PNG filter {filt}")
        out += row
        prev = row
    return width, height, bytes(out)


# --------------------------------------------------------------------------
# C emission (byte-identical to the original avatar_pipeline.py output)


def _bytes_rows(data: bytes, indent: str = "    ") -> str:
    rows = []
    for index in range(0, len(data), 16):
        rows.append(indent + ", ".join(str(v) for v in data[index : index + 16]) + ",")
    return "\n".join(rows)


def _words_rows(data: list[int], indent: str = "    ") -> str:
    rows = []
    for index in range(0, len(data), 8):
        rows.append(indent + ", ".join(f"0x{v:04x}" for v in data[index : index + 8]) + ",")
    return "\n".join(rows)


def _emit_bank(prefix: str, bank: dict) -> str:
    t = bank["target"]
    mx, my, marray = bank["mouth"]
    return (
        "    {\n"
        f"        .target = {{ {t[0]}, {t[1]}, {t[2]}, {t[3]}, {t[4]}, {{0, 0, 0}} }},\n"
        f"        .base_cell = {bank['base_cell']},\n"
        f"        .overlay_cell = {bank['overlay_cell']},\n"
        "        .overlay_x = 0,\n"
        "        .overlay_y = 0,\n"
        f"        .mouth = {{ {mx}, {my}, {prefix}_mouths_{marray} }},\n"
        "        .eye_left = " + DISABLED_EYE + ",\n"
        "        .eye_right = " + DISABLED_EYE + ",\n"
        "        .pupil_left = " + DISABLED_PUPIL + ",\n"
        "        .pupil_right = " + DISABLED_PUPIL + ",\n"
        "        .brow_left = " + DISABLED_BROW + ",\n"
        "        .brow_right = " + DISABLED_BROW + ",\n"
        "    },"
    )


def _emit_atlas_definition(pack: dict, atlas: dict, palette_name: str, palette_count: int) -> str:
    prefix = pack["prefix"]
    symbol = f"face_sprite_{prefix}_atlas"
    if atlas["variant"] is not None:
        symbol += f"_{atlas['variant']}"
    flag_tokens = pack["atlas_flags"]
    flags_text = " |\n        ".join(flag_tokens) if flag_tokens else "0"
    fallback_text = ", ".join(str(v) for v in pack["fallback_slots"])
    return (
        f"const face_sprite_atlas_t {symbol} = {{\n"
        "    .magic = FACE_SPRITE_MAGIC,\n"
        "    .version = FACE_SPRITE_VERSION,\n"
        f"    .native_width = {pack['native_width']},\n"
        f"    .native_height = {pack['native_height']},\n"
        f"    .scale = {pack['scale']},\n"
        "    .transparent_index = 0,\n"
        f"    .palette_count = {palette_count},\n"
        f"    .cell_count = {len(pack['cells'])},\n"
        f"    .mouth_slot_count = {len(pack['mouths'][0])},\n"
        f"    .viseme_map_count = {len(pack['visemes'])},\n"
        f"    .bank_count = {len(pack['banks'])},\n"
        "    .sequence_count = 0,\n"
        "    .cycle_count = 0,\n"
        f"    .flags = {flags_text},\n"
        f"    .background = 0x{atlas['background']:04x},\n"
        "    .reserved = 0,\n"
        "    .selector = FACE_SPRITE_SELECTOR_DEFAULTS,\n"
        "    .timing = FACE_SPRITE_TIMING_DEFAULTS,\n"
        f"    .fallback_slots = {{ {fallback_text} }},\n"
        "    .reserved_slots = {0, 0, 0},\n"
        f"    .palette = {palette_name},\n"
        f"    .cells = {prefix}_cells,\n"
        f"    .blob = {prefix}_blob,\n"
        f"    .blob_size = sizeof({prefix}_blob),\n"
        f"    .banks = {prefix}_banks,\n"
        f"    .viseme_map = {prefix}_visemes,\n"
        "    .sequences = NULL,\n"
        "    .cycles = NULL,\n"
        f'    .name = "{atlas["name"]}",\n'
        "};\n"
    )


def emit_atlas_c(pack: dict, cell_pixels: list[bytes]) -> str:
    prefix = pack["prefix"]
    parts: list[str] = [BANNER, f'#include "iterate/kit/avatar/{prefix}_atlas.h"\n']

    palette = pack["palette565"]
    parts.append(
        f"static const uint16_t {prefix}_palette[{len(palette)}] = {{\n"
        f"{_words_rows(palette)}\n"
        "};\n"
    )

    blob = bytearray()
    cell_lines = []
    for cell, pixels in zip(pack["cells"], cell_pixels):
        data, encoding = encode_cell(pixels)
        cell_lines.append(
            "    { "
            f"{cell['w']}, {cell['h']}, {cell['ox']}, {cell['oy']}, "
            f"{len(blob)}, {len(data)}, {encoding}, {{0, 0, 0}} "
            "},"
        )
        blob.extend(data)
    parts.append(
        f"static const uint8_t {prefix}_blob[{len(blob)}] = {{\n"
        f"{_bytes_rows(bytes(blob))}\n"
        "};\n"
    )
    parts.append(
        f"static const face_sprite_cell_t {prefix}_cells"
        f"[{len(cell_lines)}] = {{\n" + "\n".join(cell_lines) + "\n};\n"
    )

    for index, slots in enumerate(pack["mouths"]):
        parts.append(
            f"static const uint16_t {prefix}_mouths_{index}"
            f"[{len(slots)}] = {{\n    "
            + ", ".join(str(v) for v in slots)
            + ",\n};\n"
        )

    map_lines = [f"    {{ {a}, {b}, {c}, {d} }}," for a, b, c, d in pack["visemes"]]
    parts.append(
        f"static const face_sprite_viseme_map_t {prefix}_visemes"
        f"[{len(map_lines)}] = {{\n" + "\n".join(map_lines) + "\n};\n"
    )

    bank_lines = [_emit_bank(prefix, bank) for bank in pack["banks"]]
    parts.append(
        f"static const face_sprite_bank_t {prefix}_banks"
        f"[{len(bank_lines)}] = {{\n" + "\n".join(bank_lines) + "\n};\n"
    )

    for atlas in pack["atlases"]:
        if atlas["variant"] is None:
            palette_name = f"{prefix}_palette"
            palette_count = len(palette)
        else:
            palette_name = f"{prefix}_palette_{atlas['variant']}"
            variant_palette = atlas["palette565"]
            palette_count = len(variant_palette)
            parts.append(
                f"static const uint16_t {palette_name}"
                f"[{len(variant_palette)}] = {{\n"
                f"{_words_rows(variant_palette)}\n"
                "};\n"
            )
        parts.append(_emit_atlas_definition(pack, atlas, palette_name, palette_count))
    return "\n".join(parts)


def emit_catalog_inc(packs: list[dict]) -> str:
    ordered = sorted(packs, key=lambda p: p["catalog"]["slug"])
    lines = [CATALOG_BANNER.rstrip("\n")]
    for pack in ordered:
        lines.append(f'#include "iterate/kit/avatar/{pack["prefix"]}_atlas.h"')
    lines.append("")
    lines.append("static const face_avatar_entry_t GENERATED_AVATARS[] = {")
    for pack in ordered:
        cat = pack["catalog"]
        symbol = f"face_sprite_{pack['prefix']}_atlas"
        if cat["atlas_variant"] is not None:
            symbol += f"_{cat['atlas_variant']}"
        flags = " |\n            ".join(cat["render_flags"])
        lines.append("    {")
        lines.append(f'        "{cat["slug"]}",')
        lines.append(f'        "{cat["display_name"]}",')
        lines.append(f"        &{symbol},")
        lines.append(f"        {cat['width']}U,")
        lines.append(f"        {cat['height']}U,")
        lines.append(f"        {flags},")
        lines.append("    },")
    lines.append("};")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------
# Parsing the generated C (extract mode)


def _ints(text: str) -> list[int]:
    return [int(t, 0) for t in re.findall(r"0x[0-9a-fA-F]+|-?\d+", text)]


def parse_atlas_c(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    prefix_match = re.search(r"static const uint16_t (\w+)_palette\[", text)
    if not prefix_match:
        raise ValueError(f"{path}: no palette array")
    prefix = prefix_match.group(1)

    def array_body(pattern: str) -> str:
        match = re.search(pattern, text, re.DOTALL)
        if not match:
            raise ValueError(f"{path}: missing {pattern}")
        return match.group(1)

    palette = _ints(array_body(rf"uint16_t {prefix}_palette\[\d+\] = \{{(.*?)\}};"))
    blob = bytes(_ints(array_body(rf"uint8_t {prefix}_blob\[\d+\] = \{{(.*?)\}};")))

    cells = []
    cells_body = array_body(rf"face_sprite_cell_t {prefix}_cells\[\d+\] = \{{(.*?)\}};")
    for line in re.findall(r"\{ ([^{}]+), \{0, 0, 0\} \},", cells_body):
        w, h, ox, oy, offset, length, encoding = _ints(line)
        cells.append(
            {"w": w, "h": h, "ox": ox, "oy": oy, "offset": offset, "length": length, "encoding": encoding}
        )

    mouths = []
    for index in range(len(re.findall(rf"uint16_t {prefix}_mouths_\d+\[", text))):
        mouths.append(_ints(array_body(rf"uint16_t {prefix}_mouths_{index}\[\d+\] = \{{(.*?)\}};")))

    visemes_body = array_body(rf"face_sprite_viseme_map_t {prefix}_visemes\[\d+\] = \{{(.*?)\}};")
    visemes = [list(_ints(m)) for m in re.findall(r"\{ ([^{}]+) \},", visemes_body)]

    bank_re = re.compile(
        r"    \{\n"
        r"        \.target = \{ (-?\d+), (-?\d+), (-?\d+), (-?\d+), (-?\d+), \{0, 0, 0\} \},\n"
        r"        \.base_cell = (\d+),\n"
        r"        \.overlay_cell = (\d+),\n"
        r"        \.overlay_x = 0,\n"
        r"        \.overlay_y = 0,\n"
        rf"        \.mouth = \{{ (-?\d+), (-?\d+), {prefix}_mouths_(\d+) \}},\n"
        r"        \.eye_left = " + re.escape(DISABLED_EYE) + r",\n"
        r"        \.eye_right = " + re.escape(DISABLED_EYE) + r",\n"
        r"        \.pupil_left = " + re.escape(DISABLED_PUPIL) + r",\n"
        r"        \.pupil_right = " + re.escape(DISABLED_PUPIL) + r",\n"
        r"        \.brow_left = " + re.escape(DISABLED_BROW) + r",\n"
        r"        \.brow_right = " + re.escape(DISABLED_BROW) + r",\n"
        r"    \},"
    )
    banks = []
    for m in bank_re.finditer(text):
        v = [int(x) for x in m.groups()]
        banks.append(
            {"target": v[0:5], "base_cell": v[5], "overlay_cell": v[6], "mouth": [v[7], v[8], v[9]]}
        )
    declared_banks = int(re.search(rf"{prefix}_banks\[(\d+)\]", text).group(1))
    if len(banks) != declared_banks:
        raise ValueError(f"{path}: parsed {len(banks)} banks, expected {declared_banks} - unsupported bank shape")

    atlas_re = re.compile(
        r"const face_sprite_atlas_t (\w+) = \{\n"
        r"    \.magic = FACE_SPRITE_MAGIC,\n"
        r"    \.version = FACE_SPRITE_VERSION,\n"
        r"    \.native_width = (\d+),\n"
        r"    \.native_height = (\d+),\n"
        r"    \.scale = (\d+),\n"
        r"    \.transparent_index = 0,\n"
        r"    \.palette_count = (\d+),\n"
        r"    \.cell_count = (\d+),\n"
        r"    \.mouth_slot_count = (\d+),\n"
        r"    \.viseme_map_count = (\d+),\n"
        r"    \.bank_count = (\d+),\n"
        r"    \.sequence_count = 0,\n"
        r"    \.cycle_count = 0,\n"
        r"    \.flags = (.*?),\n"
        r"    \.background = 0x([0-9a-f]{4}),\n"
        r"    \.reserved = 0,\n"
        r"    \.selector = FACE_SPRITE_SELECTOR_DEFAULTS,\n"
        r"    \.timing = FACE_SPRITE_TIMING_DEFAULTS,\n"
        r"    \.fallback_slots = \{ ([^}]+) \},\n"
        r"    \.reserved_slots = \{0, 0, 0\},\n"
        r"    \.palette = (\w+),\n"
        rf"    \.cells = {prefix}_cells,\n"
        rf"    \.blob = {prefix}_blob,\n"
        rf"    \.blob_size = sizeof\({prefix}_blob\),\n"
        rf"    \.banks = {prefix}_banks,\n"
        rf"    \.viseme_map = {prefix}_visemes,\n"
        r"    \.sequences = NULL,\n"
        r"    \.cycles = NULL,\n"
        r'    \.name = "([^"]+)",\n'
        r"\};",
        re.DOTALL,
    )
    atlases = []
    atlas_flags: list[str] | None = None
    fallback_slots: list[int] | None = None
    native = None
    for m in atlas_re.finditer(text):
        (symbol, nw, nh, scale, palette_count, cell_count, mouth_count, viseme_count,
         bank_count, flags_text, background, fallback, palette_name, name) = m.groups()
        if (int(cell_count), int(mouth_count), int(viseme_count), int(bank_count)) != (
            len(cells), len(mouths[0]), len(visemes), len(banks)
        ):
            raise ValueError(f"{path}: atlas {symbol} counts disagree with parsed arrays")
        flags = [t.strip() for t in flags_text.split("|")]
        if atlas_flags is None:
            atlas_flags = flags
            fallback_slots = _ints(fallback)
            native = (int(nw), int(nh), int(scale))
        elif flags != atlas_flags or _ints(fallback) != fallback_slots or native != (int(nw), int(nh), int(scale)):
            raise ValueError(f"{path}: atlas {symbol} diverges in shared fields")
        base_symbol = f"face_sprite_{prefix}_atlas"
        if symbol == base_symbol:
            variant = None
            if palette_name != f"{prefix}_palette":
                raise ValueError(f"{path}: base atlas uses unexpected palette {palette_name}")
            variant_palette = None
        else:
            variant = symbol[len(base_symbol) + 1 :]
            if palette_name != f"{prefix}_palette_{variant}":
                raise ValueError(f"{path}: variant atlas uses unexpected palette {palette_name}")
            variant_palette = _ints(array_body(rf"uint16_t {palette_name}\[\d+\] = \{{(.*?)\}};"))
            if len(variant_palette) != int(palette_count):
                raise ValueError(f"{path}: variant palette count mismatch")
        atlases.append(
            {"variant": variant, "name": name, "background": int(background, 16), "palette565": variant_palette}
        )
    if not atlases:
        raise ValueError(f"{path}: no atlas definitions matched the expected template")

    # Decode every cell and prove the blob is a contiguous concatenation that
    # our encoder reproduces byte-for-byte.
    cell_pixels: list[bytes] = []
    cursor = 0
    for index, cell in enumerate(cells):
        if cell["offset"] != cursor:
            raise ValueError(f"{path}: cell {index} not contiguous in blob")
        data = blob[cell["offset"] : cell["offset"] + cell["length"]]
        pixels = data if cell["encoding"] == 0 else unpackbits(data, cell["w"] * cell["h"])
        if len(pixels) != cell["w"] * cell["h"]:
            raise ValueError(f"{path}: cell {index} pixel count mismatch")
        redata, reenc = encode_cell(pixels)
        if redata != data or reenc != cell["encoding"]:
            raise ValueError(f"{path}: cell {index} does not re-encode identically")
        cell_pixels.append(pixels)
        cursor += cell["length"]
    if cursor != len(blob):
        raise ValueError(f"{path}: blob has {len(blob) - cursor} trailing bytes")

    pack = {
        "prefix": prefix,
        "native_width": native[0],
        "native_height": native[1],
        "scale": native[2],
        "transparent_index": 0,
        "palette565": palette,
        "atlas_flags": atlas_flags,
        "fallback_slots": fallback_slots,
        "atlases": atlases,
        "cells": [{k: c[k] for k in ("w", "h", "ox", "oy")} for c in cells],
        "mouths": mouths,
        "visemes": visemes,
        "banks": banks,
    }
    return pack | {"_cell_pixels": cell_pixels}


def parse_catalog_inc(path: Path) -> dict[str, dict]:
    text = path.read_text(encoding="utf-8")
    entry_re = re.compile(
        r"    \{\n"
        r'        "([^"]+)",\n'
        r'        "([^"]+)",\n'
        r"        &face_sprite_(\w+?)_atlas(?:_(original))?,\n"
        r"        (\d+)U,\n"
        r"        (\d+)U,\n"
        r"        ((?:\w+ \|\n            )*\w+),\n"
        r"    \},"
    )
    entries: dict[str, dict] = {}
    for m in entry_re.finditer(text):
        slug, display, prefix, variant, width, height, flags_text = m.groups()
        entries[prefix] = {
            "slug": slug,
            "display_name": display,
            "atlas_variant": variant,
            "width": int(width),
            "height": int(height),
            "render_flags": [t.strip() for t in flags_text.replace("\n", " ").split("|")],
        }
    if not entries:
        raise ValueError(f"{path}: no catalog entries matched")
    return entries


# --------------------------------------------------------------------------
# Sprite map layout


def layout_cells(pack: dict, cell_pixels: list[bytes]) -> tuple[int, int, bytes]:
    """Shelf-pack cells in index order; records x/y into pack['cells']."""
    x = y = shelf_h = sheet_w = 0
    placements = []
    for cell in pack["cells"]:
        if x and x + cell["w"] > SHEET_MAX_WIDTH:
            y += shelf_h
            x = shelf_h = 0
        placements.append((x, y))
        cell["x"], cell["y"] = x, y
        shelf_h = max(shelf_h, cell["h"])
        sheet_w = max(sheet_w, x + cell["w"])
        x += cell["w"]
    sheet_h = y + shelf_h
    sheet = bytearray(sheet_w * sheet_h)
    for cell, (cx, cy), pixels in zip(pack["cells"], placements, cell_pixels):
        for row in range(cell["h"]):
            dst = (cy + row) * sheet_w + cx
            sheet[dst : dst + cell["w"]] = pixels[row * cell["w"] : (row + 1) * cell["w"]]
    return sheet_w, sheet_h, bytes(sheet)


def cells_from_sheet(pack: dict, sheet_w: int, sheet_h: int, sheet: bytes) -> list[bytes]:
    pixels = []
    for cell in pack["cells"]:
        if cell["x"] + cell["w"] > sheet_w or cell["y"] + cell["h"] > sheet_h:
            raise ValueError(f"cell rect {cell} exceeds sprite map {sheet_w}x{sheet_h}")
        buf = bytearray()
        for row in range(cell["h"]):
            src = (cell["y"] + row) * sheet_w + cell["x"]
            buf += sheet[src : src + cell["w"]]
        pixels.append(bytes(buf))
    return pixels


# --------------------------------------------------------------------------
# JSON formatting: pretty at the top level, inline leaf arrays/objects


def dump_pack_json(pack: dict) -> str:
    def inline(value) -> str:
        return json.dumps(value, ensure_ascii=False, separators=(", ", ": "))

    lines = ["{"]
    scalars = ("prefix", "native_width", "native_height", "scale", "transparent_index")
    for key in scalars:
        lines.append(f'  "{key}": {inline(pack[key])},')
    for key in ("palette565", "atlas_flags", "fallback_slots"):
        lines.append(f'  "{key}": {inline(pack[key])},')
    lines.append('  "atlases": [')
    for atlas in pack["atlases"]:
        lines.append(f"    {inline(atlas)},")
    lines[-1] = lines[-1].rstrip(",")
    lines.append("  ],")
    for key in ("cells", "mouths", "visemes", "banks"):
        lines.append(f'  "{key}": [')
        for item in pack[key]:
            lines.append(f"    {inline(item)},")
        lines[-1] = lines[-1].rstrip(",")
        lines.append("  ],")
    lines.append(f'  "catalog": {inline(pack["catalog"])}')
    lines.append("}")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------
# Commands


def pack_paths(pack: dict) -> tuple[Path, Path, Path]:
    short = re.fullmatch(r"fspp_(\w+)_cores3_fine", pack["prefix"]).group(1)
    return ASSETS / f"{short}.json", ASSETS / f"{short}.png", SRC / f"{pack['prefix']}_atlas.c"


def cmd_generate() -> int:
    packs = []
    for json_path in sorted(ASSETS.glob("*.json")):
        pack = json.loads(json_path.read_text(encoding="utf-8"))
        png_path = json_path.with_suffix(".png")
        sheet_w, sheet_h, sheet = png_read(png_path)
        cell_pixels = cells_from_sheet(pack, sheet_w, sheet_h, sheet)
        _, _, c_path = pack_paths(pack)
        c_path.write_text(emit_atlas_c(pack, cell_pixels), encoding="utf-8")
        print(f"generated: {c_path.relative_to(FIRMWARE)}")
        packs.append(pack)
    if not packs:
        print(f"no pack descriptors found in {ASSETS}", file=sys.stderr)
        return 1
    CATALOG_INC.write_text(emit_catalog_inc(packs), encoding="utf-8")
    print(f"generated: {CATALOG_INC.relative_to(FIRMWARE)}")
    return 0


def cmd_extract() -> int:
    catalog = parse_catalog_inc(CATALOG_INC)
    ASSETS.mkdir(parents=True, exist_ok=True)
    packs = []
    for c_path in sorted(SRC.glob("fspp_*_atlas.c")):
        pack = parse_atlas_c(c_path)
        cell_pixels = pack.pop("_cell_pixels")
        if pack["prefix"] not in catalog:
            raise ValueError(f"{c_path}: no catalog entry for {pack['prefix']}")
        pack["catalog"] = catalog[pack["prefix"]]
        sheet_w, sheet_h, sheet = layout_cells(pack, cell_pixels)

        # Round-trip proof before writing anything.
        rebuilt = emit_atlas_c(pack, cells_from_sheet(pack, sheet_w, sheet_h, sheet))
        original = c_path.read_text(encoding="utf-8")
        if rebuilt != original:
            raise ValueError(f"{c_path}: extraction does not round-trip byte-identically")

        json_path, png_path, _ = pack_paths(pack)
        png_write(png_path, sheet_w, sheet_h, sheet, pack["palette565"])
        json_path.write_text(dump_pack_json(pack), encoding="utf-8")
        print(f"extracted: {json_path.relative_to(FIRMWARE)} + {png_path.name} ({sheet_w}x{sheet_h})")
        packs.append(pack)
    rebuilt_inc = emit_catalog_inc(packs)
    if rebuilt_inc != CATALOG_INC.read_text(encoding="utf-8"):
        raise ValueError(f"{CATALOG_INC}: catalog does not round-trip byte-identically")
    return 0


def main() -> int:
    mode = sys.argv[1] if len(sys.argv) > 1 else "generate"
    if mode == "generate":
        return cmd_generate()
    if mode == "extract":
        return cmd_extract()
    print(__doc__, file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
