#!/usr/bin/env python3
"""Bake name=file WAV pairs from WORK into static 16 kHz mono PCM16LE sounds.

Sources are the Apache-2.0 Home Assistant Voice PE press chime and OpenAI
marin announcements. tools/baked-sounds.cmake supplies each board's measured
wake trim and gain.
"""
import argparse
from fractions import Fraction
import pathlib
import struct
import wave


def pcm_of(path):
    """Read a normalized 16 kHz mono PCM16 WAV payload."""
    with wave.open(str(path), "rb") as input_wav:
        if (
            input_wav.getnchannels() != 1
            or input_wav.getsampwidth() != 2
            or input_wav.getframerate() != 16000
            or input_wav.getcomptype() != "NONE"
        ):
            raise SystemExit(f"{path} must be uncompressed 16 kHz mono PCM16.")
        return input_wav.readframes(input_wav.getnframes())


def trim_wake(pcm):
    """Keep the 0.4 s audible body and fade its last 40 ms, as bench-proven."""
    samples = list(struct.unpack("<%dh" % (len(pcm) // 2), pcm))
    samples = samples[:6400]
    for i in range(640):
        j = len(samples) - 640 + i
        samples[j] = samples[j] * (640 - 1 - i) // 640
    return struct.pack("<%dh" % len(samples), *samples)


def apply_gain(pcm, gain):
    """Scale with signed floor division and saturate before packing PCM16."""
    samples = struct.unpack("<%dh" % (len(pcm) // 2), pcm)
    scaled = []
    for sample in samples:
        boosted = sample * gain.numerator // gain.denominator
        scaled.append(max(-32768, min(32767, boosted)))
    return struct.pack("<%dh" % len(scaled), *scaled)


def main():
    """Write the C include to stdout in the supplied sound order."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("work", type=pathlib.Path)
    parser.add_argument("sounds", nargs="+", metavar="name=file")
    parser.add_argument("--output", type=pathlib.Path, required=True)
    parser.add_argument("--trim-wake", action="store_true")
    parser.add_argument("--gain", type=Fraction, default=Fraction(1))
    args = parser.parse_args()
    names = [pair.split("=", 1) for pair in args.sounds]
    with args.output.open("w") as output:
        print("/* GENERATED by make-sounds.py — do not edit. 16 kHz mono PCM16LE. */", file=output)
        for cname, fname in names:
            pcm = pcm_of(args.work / fname)
            if args.trim_wake and cname == "chime_press":
                pcm = trim_wake(pcm)
            if args.gain != 1:
                pcm = apply_gain(pcm, args.gain)
            print(f"static const uint8_t sound_{cname}[] = {{", file=output)
            for i in range(0, len(pcm), 24):
                print("  " + ",".join(str(b) for b in pcm[i:i+24]) + ",", file=output)
            print("};", file=output)


if __name__ == "__main__":
    main()
